defaults: &defaults
  adapter: mysql2
  reconnect: false
  username: root
  password:
  host: localhost
  pool: 5
  encoding: utf8

development:
  <<: *defaults
  database: learnopedia_dev

test:
  <<: *defaults
  database: learnopedia_test